services:
  - type: web
    name: gazouhenkan
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
